name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # specify versions to test
      INT_NODECORE_VERSION: "0.4.13-rc.14"
      INT_APM_VERSION: "0.4.13-rc.13"
      INT_BTCSQ_VERSION: "master-47363b0"
      INT_LOG_LEVEL: "DEBUG"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      - run: ./gradlew build -x test
      - run: ./gradlew test
